server:
  global:
    scrape_interval: 15s
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClassName: "ebs-sc"  # EBS CSI 드라이버용 StorageClass로 변경
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

alertmanager:
  persistentVolume:
    enabled: true
    size: 2Gi
    storageClassName: "ebs-sc"  # EBS CSI 드라이버용 StorageClass로 변경
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

extraScrapeConfigs: |
  - job_name: 'opentelemetry-collector'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: '.*opentelemetrycollector.*'
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: '8889'
        action: keep