global:
  scrape_interval: 15s

server:
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: "efs-sc"
    accessModes:
      - ReadWriteMany
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

alertmanager:
  persistentVolume:
    enabled: true
    size: 2Gi
    storageClass: "efs-sc"
    accessModes:
      - ReadWriteMany
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Prometheus 서버와 Alertmanager가 EFS를 사용할 수 있도록 securityContext 추가
commonSecurityContext:
  runAsUser: 65534  # nobody 사용자
  fsGroup: 65534    # nobody 그룹

extraScrapeConfigs: |
  - job_name: 'opentelemetry-collector'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: '.*opentelemetrycollector.*'
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: '8889'
        action: keep

# 스토리지 프로비저닝 문제를 방지하기 위해 추가
storageClass:
  name: efs-sc